### ISSUE TITLE
protect:entity_attack_player no effect

### ISSUE THREAD

**Issue by Draecal** [TheNextLvl-net/protect#19]
I was expecting this protection to prevent mobs from attacking players but after setting its value to **false** I see no effect

**Comment by NonSwag** [comment]
Thanks for reporting this issue, I have published a fix for it.

**Comment by Draecal** [comment]
After updating checked and still this flag has no effect

**Comment by NonSwag** [comment]
please make sure you are indeed using protect [version 2.1.2](https://hangar.papermc.io/TheNextLvl/Protect/versions/2.1.2)
and the flag is really set to false

**Comment by NonSwag** [comment]
I tested it myself to verify and it works as expected

**Comment by Draecal** [comment]
![image](https://github.com/user-attachments/assets/6184eaf8-b92b-47a0-942a-388e00137a19)
![image](https://github.com/user-attachments/assets/325b497b-7e1a-4740-a19f-792b97e9964c)

**Comment by NonSwag** [comment]
The area with the highest priority at the position of the entity is the one who counts
